// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMh1vsVUrhsjqbMCKYBw1lc7ZR15Eu14',
    appId: '1:719657927295:web:5dae31588193570cb1f54a',
    messagingSenderId: '719657927295',
    projectId: 'flutter-training-chat-app',
    authDomain: 'flutter-training-chat-app.firebaseapp.com',
    databaseURL: 'https://flutter-training-chat-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLJT681eeifgpgrhqBYBP7ccHba4t1gs',
    appId: '1:719657927295:android:0feb6fa5bee59417b1f54a',
    messagingSenderId: '719657927295',
    projectId: 'flutter-training-chat-app',
    databaseURL: 'https://flutter-training-chat-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7pukasmx6l4RZYh5sXiB6zSqlgHXDKc',
    appId: '1:719657927295:ios:fefa32dc4d4a7825b1f54a',
    messagingSenderId: '719657927295',
    projectId: 'flutter-training-chat-app',
    databaseURL: 'https://flutter-training-chat-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-chat-app.appspot.com',
    iosClientId: '719657927295-fii44j5kl0usl9k51cq3c2jc32n0kimg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
